eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: localhost

server:
  port: 9000
spring:
  application:
    name: gateway-server-dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: departments-dev
          uri: http://localhost:9006
          predicates:
            - Path=/api/v1/deparments/**
        - id: students-dev
          uri: http://localhost:9005
          predicates:
            - Path=/api/v1/students/**

management:
  tracing:
    sampling:
      probability: 1.0
