eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    hostname: localhost

server:
  port: 9002
spring:
  application:
    name: gateway-server-qa
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: departments-qa
          uri: http://localhost:9007
          predicates:
            - Path=/api/v1/deparments/**
        - id: schools
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
      probability: 1.0
