server:
  port: 9001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        enabled: true
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: music-route
          uri: lb://music-service
          predicates:
            - Path=/music/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: music-route
          uri: lb://messaging-service
          predicates:
            - Path=/messaging/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: music-route
          uri: lb://task-scheduler-service
          predicates:
            - Path=/task-scheduler/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka**
  instance:
    hostname: localhost