spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    server-url:
       defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
  